/*module "clixxapp" {
    source    = "./clixxapp"
    AWS_REGION = var.AWS_REGION
    PATH_TO_PRIVATE_KEY=var.PATH_TO_PRIVATE_KEY
    PATH_TO_PUBLIC_KEY=var.PATH_TO_PUBLIC_KEY
    #PROD_DB_SNAPSHOT=var.PROD_DB_SNAPSHOT
    #AMIS=var.AMISE
    AWS_SECRET_KEY=var.AWS_SECRET_KEY
    AWS_ACCESS_KEY=var.AWS_ACCESS_KEY
    DB_NAME = var.DB_NAME
    DB_USER = var.DB_USER
    DB_PASSWORD = var.DB_PASSWORD
    RDS_ENDPOINT = var.RDS_ENDPOINT
} 
*/
module "ebs" {
    source    = "./ebs"
    AWS_REGION = var.AWS_REGION
    PATH_TO_PRIVATE_KEY=var.PATH_TO_PRIVATE_KEY
    PATH_TO_PUBLIC_KEY=var.PATH_TO_PUBLIC_KEY
    #PROD_DB_SNAPSHOT=var.PROD_DB_SNAPSHOT
    AMIS=var.AMIS
    AWS_SECRET_KEY=var.AWS_SECRET_KEY
    AWS_ACCESS_KEY=var.AWS_ACCESS_KEY
    #DB_NAME = var.DB_NAME
    #DB_USER = var.DB_USER
    #DB_PASSWORD = var.DB_PASSWORD
    #RDS_ENDPOINT = var.RDS_ENDPOINT
} 
