AWS_ACCESS_KEY="AKIAR3SALBG4GJ3K7AV6"
AWS_SECRET_KEY="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"
AWS_REGION="us-east-1"
DB_NAME="wordpressdb-tf"
DB_USER="wordpressuser-tf"
DB_PASSWORD="stackinc"
#DB_HOST
